import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'



export default function Home({}) {
  return (
    <div className={styles.container}>
      <Head>
        <title> SJ · Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="color-name text-right ">
        <h1 className="text-5xl font-bold span-name">
          <span>S</span>
          <span>T</span>
          <span>E</span>
          <span>P</span>
          <span>H</span>
          <span>E</span>
          <span>N</span>
          <span>N</span>
          <span>A</span>
          <br />
          <span>J</span>
          <span>E</span>
          <span>M</span>
          <span>A</span>
          <span>E</span>
        </h1>
        <h3 className="links transform">
          <span className=" hover:text-red-700 animate-pulse">
            <Link href='/about' className="link-about hover:bg-red-700">About</Link>
          </span>
          <span> · </span>
          <span className=" hover:text-green-700 animate-pulse">
            <Link href='/projects' className="link-projects"> Projects</Link>
          </span>
          <span> · </span>
          <span className=" hover:text-pink-700 animate-pulse">
            <Link href='/resume' class> Resume</Link>
          </span>
        </h3>
      </div>
    </div>
  )
}
