import Navbar from "./components/Navbar"
import Spots from "./components/layout"
import Link from "next/link"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
const Return = () => {
    return(
        <div className={styles.container}>
      <Head>
        <title> SJ · Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="color-name text-right ">
        <h1 className="text-5xl font-bold span-name">
          <span>T</span>
          <span>H</span>
          <span>A</span>
          <span>N</span>
          <span>K</span>
          <br />
          <span>Y</span>
          <span>O</span>
          <span>U</span>  
        </h1>
        <h3 className="links transform">
          <span className=" hover:text-red-700 animate-pulse">
            <Link href='/about' className="link-about hover:bg-red-700">About</Link>
          </span>
          <span> · </span>
          <span className=" hover:text-green-700 animate-pulse">
            <Link href='/projects' className="link-projects"> Projects</Link>
          </span>
          <span> · </span>
          <span className=" hover:text-pink-700 animate-pulse">
            <Link href='/resume' class> Resume</Link>
          </span>
        </h3>
      </div>
    </div>
    )
}

export default Return